global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Flink JobManager metrics
  - job_name: 'flink-jobmanager'
    static_configs:
      - targets: ['flink-jobmanager:9249']
        labels:
          component: 'jobmanager'

  # Flink TaskManager metrics
  - job_name: 'flink-taskmanager'
    static_configs:
      - targets: ['flink-taskmanager:9249']
        labels:
          component: 'taskmanager'

  # Kafka metrics (JMX exporter would be needed)
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9101']
        labels:
          service: 'kafka'

  # Redis exporter (would need to add redis_exporter service)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
        labels:
          service: 'redis'