{{- if .Values.networkPolicy.enabled }}
apiVersion: {{ include "model-serving.networkPolicy.apiVersion" . }}
kind: NetworkPolicy
metadata:
  name: {{ include "model-serving.fullname" . }}
  labels:
    {{- include "model-serving.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "model-serving.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  {{- with .Values.networkPolicy.ingress }}
  ingress:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.networkPolicy.egress }}
  egress:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}