apiVersion: v1
kind: Service
metadata:
  name: {{ include "model-serving.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "model-serving.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "model-serving.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: 80
      targetPort: http
