apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: iris-model
  labels:
    version: v1
spec:
  predictors:
    - name: iris-predictor
      replicas: 1
      graph:
        name: classifier
        implementation: SKLEARN_SERVER
        modelUri: gs://models/iris/v1
      componentSpecs:
        - spec:
            containers:
              - name: classifier
                image: seldonio/sklearnserver:1.14.0
