apiVersion: batch/v1
kind: Job
metadata:
  name: train-mnist
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: trainer
        image: pytorch/pytorch:latest
        command: ["python","-c","import time; print('training'); time.sleep(60)"]
        resources:
          limits:
            nvidia.com/gpu: 1
      tolerations:
      - key: nvidia.com/gpu
        operator: Exists
  backoffLimit: 1
