apiVersion: batch/v1
kind: CronJob
metadata:
  name: train-mnist
spec:
  schedule: "0 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: trainer
            image: pytorch/pytorch:latest
            command: ["python","-c","import time; print('training'); time.sleep(60)"]
            resources:
              limits:
                nvidia.com/gpu: 1
            securityContext:
              allowPrivilegeEscalation: false
              runAsNonRoot: true
              runAsUser: 1000
              capabilities:
                drop:
                - ALL
          tolerations:
          - key: nvidia.com/gpu
            operator: Exists
      backoffLimit: 1
