apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: iris-success-rate
spec:
  args:
    - name: service-name
    - name: prometheus-address
      value: http://prometheus.istio-system:9090  # Default value, can be overridden
  metrics:
    - name: success-rate
      interval: 1m
      count: 3
      # Check that all three measurements meet the threshold
      successCondition: result[0] >= 0.95 && result[1] >= 0.95 && result[2] >= 0.95
      failureCondition: result[0] < 0.95 || result[1] < 0.95 || result[2] < 0.95
      provider:
        prometheus:
          address: "{{args.prometheus-address}}"
          query: |
            sum(rate(istio_request_total{destination_service_name="{{args.service-name}}",response_code=~"2.."}[1m]))
            /
            sum(rate(istio_request_total{destination_service_name="{{args.service-name}}"}[1m]))
