apiVersion: platform.orbis.dev/v1alpha1
kind: Cluster
metadata:
  name: prod-eu
  namespace: default
  labels:
    environment: production
    region: europe-west1
    provider: gcp
spec:
  compositionRef:
    name: gcp-xcluster
  parameters:
    provider: gcp
    region: europe-west1
    nodeCount: 3
    nodeSize: medium
    kubernetesVersion: v1.28.0
    networkCIDR: 10.1.0.0/16
    enableLogging: true
    enableMonitoring: true
    tags:
      Environment: production
      ManagedBy: crossplane
      Project: ml-platform
  writeConnectionSecretToRef:
    name: prod-eu-kubeconfig
    namespace: crossplane-system
