image:
  repository: myregistry/my-model
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

gpu:
  enabled: false
  nodeSelector:
    nvidia.com/gpu.present: "true"
  tolerations:
    - key: nvidia.com/gpu
      operator: Exists
      effect: NoSchedule

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPU: 80

prometheus:
  scrape: true
  port: http
